### ISSUE TITLE
插件载入报错

### ISSUE THREAD

**Issue by iqovo** [MakesYT/chatsync_bukkit#1]
Could not load 'plugins\chatsync_bukkit-2.3.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `top.ncserver.chatsync.Chatsync'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88) ~[PluginClassLoader.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[SimplePluginManager.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [SimplePluginManager.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:359) [CraftServer.class:git-CatServer-1.12.2-8d58cdb8]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:340) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
Caused by: java.lang.ClassNotFoundException: Failed to remap class top.ncserver.chatsync.Chatsync
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:231) ~[PluginClassLoader.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:129) ~[PluginClassLoader.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-8d58cdb8]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_341]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_341]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_341]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_341]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-8d58cdb8]
	... 8 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:228) ~[JarRemapper.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:196) ~[PluginClassLoader.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:129) ~[PluginClassLoader.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-8d58cdb8]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_341]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_341]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_341]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_341]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-8d58cdb8]
	... 8 more

**Comment by Maklith** [comment]
这个bug之前发现了编译版本使用错了，使用的11导致8无法兼容，稍后我会更新

**Comment by Maklith** [comment]
已修复
